Домашнее задание 1
JamesDeGrizz/LigaLessons pull request #2
Opened 2024-12-17 00:22 UTC by JamesDeGrizz

2024-12-18 09:47 UTC, Fixey requested changes

2024-12-18 09:47 UTC, Fixey commented on src/main/java/ru/hofftech/liga/lessons/controller/ConsoleController.java
> +            switch (command) {
Лучше сделай  через паттерн стратегия для каждого метода

2024-12-18 09:47 UTC, Fixey commented on src/main/java/ru/hofftech/liga/lessons/controller/ConsoleController.java
> +                    if (algorithm == null || algorithm < 0 || algorithm > 1) {
Если увеличатся, то уже будет case. Сделай лучше не 0,1 а к примеру enum и сделай стратегию

2024-12-18 09:47 UTC, Fixey commented on src/main/java/ru/hofftech/liga/lessons/model/Package.java
> +        return maxWidth > 0 && maxHeight > 0 && content != null && !content.isEmpty() &&
Может стоит разбить? И написать ошибки под каждую, а то свалилась с валидацией, а почему - непонятно

2024-12-18 09:47 UTC, Fixey commented on src/main/java/ru/hofftech/liga/lessons/model/Command.java
> +public enum Command {
Вынеси енам в отдельную папку

2024-12-18 09:47 UTC, Fixey commented on src/main/java/ru/hofftech/liga/lessons/model/PlacingAlgorithm.java
> +public enum PlacingAlgorithm {
Вынеси енам в отдельную папку

2024-12-18 09:47 UTC, Fixey commented on src/main/java/ru/hofftech/liga/lessons/model/Truck.java
> +public class Truck {
Почему где то ты используешь конструкторы, а где то ломбок?) Сделай через ломбок)

2024-12-18 09:47 UTC, Fixey commented on src/main/java/ru/hofftech/liga/lessons/repository/FileRepository.java
> +public class FileRepository {
Почему это репозиторий? Это же сервис

2024-12-18 09:47 UTC, Fixey commented on src/main/java/ru/hofftech/liga/lessons/controller/ConsoleController.java
> +package ru.hofftech.liga.lessons.controller;
Думаю что все же это не lessons, это сервис по загрузке. Название проекта другое. Сюда не будем все домашки складывать, на скок я понимаю

2024-12-18 09:47 UTC, Fixey commented on src/test/java/ru/hofftech/liga/lessons/service/TruckContentServiceTest.java
> +        var pkg = new Package(Arrays.asList("333"));
List.of

2024-12-18 09:47 UTC, Fixey commented on src/main/java/ru/hofftech/liga/lessons/service/LogisticServiceFactory.java
> +            default -> throw new IllegalArgumentException("Неизвестный алгоритм размещения: " + algorithm);
в данном случае default не нужен, так как ты используешь enum и отличные какие-то значения не имеются. А логику которая не используется лучше не хранить

2024-12-18 09:47 UTC, Fixey commented on src/main/java/ru/hofftech/liga/lessons/controller/ConsoleController.java
> +                    log.info("Посылки упакованы в грузовики:");
У тебя этот же комментарий уже есть внутри этого метода. Лучше пускай комментрии будут о начале и конце если хочешь внутри методов и стоит их увести на уровень дебаг, а то в этих комментариях по факту можно запутаться

2024-12-18 19:56 UTC, JamesDeGrizz commented on src/main/java/ru/hofftech/liga/lessons/model/Package.java
> +        return maxWidth > 0 && maxHeight > 0 && content != null && !content.isEmpty() &&
вообще убрал проверку валидности

2024-12-18 19:56 UTC, JamesDeGrizz commented on src/main/java/ru/hofftech/liga/lessons/controller/ConsoleController.java
> +                    if (algorithm == null || algorithm < 0 || algorithm > 1) {
там дальше как раз идет приведение к енаму

2024-12-18 19:57 UTC, JamesDeGrizz commented on src/main/java/ru/hofftech/liga/lessons/controller/ConsoleController.java
> +            switch (command) {
здесь, честно говоря, не понимаю о какой стратегии идёт речь, если реакция на первый кейс - это простой return, а на второй - continue

2024-12-18 19:58 UTC, JamesDeGrizz commented on src/main/java/ru/hofftech/liga/lessons/model/Command.java
> +public enum Command {
вынес

2024-12-18 19:58 UTC, JamesDeGrizz commented on src/main/java/ru/hofftech/liga/lessons/model/PlacingAlgorithm.java
> +public enum PlacingAlgorithm {
вынес

2024-12-18 19:58 UTC, JamesDeGrizz commented on src/main/java/ru/hofftech/liga/lessons/model/Truck.java
> +public class Truck {
справедливо. Это рудимент, когда я пытался вкорячить в конструктор проверки) 
убрал, спасибо

2024-12-18 20:00 UTC, JamesDeGrizz commented on src/main/java/ru/hofftech/liga/lessons/repository/FileRepository.java
> +public class FileRepository {
обсудили в телеграме. Переименовал, перенёс в сервисы

2024-12-18 20:02 UTC, JamesDeGrizz commented on src/main/java/ru/hofftech/liga/lessons/controller/ConsoleController.java
> +package ru.hofftech.liga.lessons.controller;
ок, переименовал

2024-12-18 20:02 UTC, JamesDeGrizz commented on src/test/java/ru/hofftech/liga/lessons/service/TruckContentServiceTest.java
> +        var pkg = new Package(Arrays.asList("333"));
спасибо, поправил

2024-12-18 20:02 UTC, JamesDeGrizz commented on src/main/java/ru/hofftech/liga/lessons/service/LogisticServiceFactory.java
> +            default -> throw new IllegalArgumentException("Неизвестный алгоритм размещения: " + algorithm);
ок, убрал

2024-12-18 20:05 UTC, JamesDeGrizz commented on src/main/java/ru/hofftech/liga/lessons/controller/ConsoleController.java
> +                    log.info("Посылки упакованы в грузовики:");
ок, убрал

2024-12-19 07:39 UTC, Fixey commented on src/main/java/ru/hofftech/liga/lessons/controller/ConsoleController.java
> +            switch (command) {
Изучи этот паттер. По сути там тоже свичи используются, ток код в одном месте не хранится, лечге читается и к SOLID выполняется

2024-12-19 21:11 UTC, Fixey requested changes

2024-12-19 21:11 UTC, Fixey commented on src/main/java/ru/hofftech/liga/lessons/packageloader/model/Truck.java
> +public class Truck {
Сущность лишняя, непонятно зачем нужна такая обертка

2024-12-19 21:11 UTC, Fixey commented on src/main/java/ru/hofftech/liga/lessons/packageloader/controller/ConsoleController.java
> +                        log.info(truck.toString());
лучше использовать log.info("{}",truck)

2024-12-19 22:47 UTC, JamesDeGrizz commented on src/main/java/ru/hofftech/liga/lessons/controller/ConsoleController.java
> +            switch (command) {
отрефачил

2024-12-19 22:48 UTC, JamesDeGrizz commented on src/main/java/ru/hofftech/liga/lessons/packageloader/model/Truck.java
> +public class Truck {
я скорее тогда перенесу content внутрь truck

2024-12-19 22:48 UTC, JamesDeGrizz commented on src/main/java/ru/hofftech/liga/lessons/packageloader/controller/ConsoleController.java
> +                        log.info(truck.toString());
ок, переделал

2024-12-20 07:45 UTC, Fixey requested changes

2024-12-20 07:45 UTC, Fixey commented on src/main/java/ru/hofftech/liga/lessons/packageloader/service/UserCommandService.java
> +        if (command.equals("help")) {
А чего help не вынес?

2024-12-20 07:47 UTC, Fixey requested changes

2024-12-20 07:47 UTC, Fixey commented on src/main/java/ru/hofftech/liga/lessons/packageloader/controller/ConsoleController.java
> +            switch (command) {
Вынеси в отедльный класс этот селектор.

2024-12-20 08:43 UTC, JamesDeGrizz commented on src/main/java/ru/hofftech/liga/lessons/packageloader/service/UserCommandService.java
> +        if (command.equals("help")) {
вынес

2024-12-20 08:43 UTC, JamesDeGrizz commented on src/main/java/ru/hofftech/liga/lessons/packageloader/controller/ConsoleController.java
> +            switch (command) {
вынес

2024-12-20 09:42 UTC, Fixey requested changes

2024-12-20 09:42 UTC, Fixey commented on src/main/java/ru/hofftech/liga/lessons/packageloader/service/UserCommandProcessorService.java
> +            userCommandServiceFactory.getUserCommandService(command).execute();
Разбей на две строки

2024-12-20 09:42 UTC, Fixey commented on src/main/java/ru/hofftech/liga/lessons/packageloader/model/Package.java
> +            builder.append(line + "\r\n");
используй append

2024-12-20 10:21 UTC, Fixey requested changes

2024-12-20 10:21 UTC, Fixey commented on src/main/java/ru/hofftech/liga/lessons/packageloader/model/Truck.java
> +    private char[][] content;
доленж быть final

2024-12-20 10:21 UTC, Fixey commented on src/main/java/ru/hofftech/liga/lessons/packageloader/service/UserConsoleService.java
> +    private Scanner scanner;
final

2024-12-20 10:36 UTC, JamesDeGrizz commented on src/main/java/ru/hofftech/liga/lessons/packageloader/service/UserCommandProcessorService.java
> +            userCommandServiceFactory.getUserCommandService(command).execute();
разбил

2024-12-20 10:36 UTC, JamesDeGrizz commented on src/main/java/ru/hofftech/liga/lessons/packageloader/model/Package.java
> +            builder.append(line + "\r\n");
переделал

2024-12-20 10:36 UTC, JamesDeGrizz commented on src/main/java/ru/hofftech/liga/lessons/packageloader/model/Truck.java
> +    private char[][] content;
+

2024-12-20 10:37 UTC, JamesDeGrizz commented on src/main/java/ru/hofftech/liga/lessons/packageloader/service/UserConsoleService.java
> +    private Scanner scanner;
+

2024-12-20 11:32 UTC, Fixey approved these changes

2024-12-20 11:32 UTC, merged